name: Merge Pull Requests
description: Merge all pull requests
inputs:
  GITHUB_TOKEN:
    required: true
    type: string
runs:
  using: composite
  steps:
    - name: Merge pull requests
      shell: sh
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        echo =====
        git branch --show-current
        echo =====
        git branch -a
        echo =====
        # git fetch --unshallow origin $()
        echo =====
        for pr_num in $(gh pr list --search "draft:false" --json number --jq ".[].number" | sort)
        do
          git pull --no-rebase origin refs/pull/${pr_num}/merge
        done
