name: Merge Pull Requests
description: Merge all pull requests
inputs:
  GITHUB_TOKEN:
    required: true
    type: string
runs:
  using: composite
  steps:
    - name: Merge pull requests
      shell: sh
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git branch --show-current
        git branch -a
        git fetch --unshallow origin $(git branch --show-current)
        git branch -a
        for pr_num in $(gh pr list --search "draft:false" --json number --jq ".[].number")
        do
          git pull --no-rebase origin refs/pull/${pr_num}/merge
        done
