title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please briefly describe the problem
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Please describe the steps to reproduce
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Please describe expected behavior
      placeholder: |
        1. foo
        2. bar
        3. ...
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: Please describe actual behavior
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please describe the execution environment.
      placeholder: |
        - cpu arch:
        - os:
        - software version:
        - etc.
    validations:
      required: false
  - type: textarea
    id: cause
    attributes:
      label: Cause
      description: Please describe the cause if you know
    validations:
      required: false
