name: Nimble Test
description: Exec nimble test
runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and Push Base
      uses: docker/build-push-action@v4
      with:
        context: .
        target: base
        tags: ci-test-base
        cache-from: |
          type=gha,scope=ci-test-base
        cache-to: type=gha,mode=max,scope=ci-test-base
        load: true
    - name: Nimble Test
      shell: sh
      run: docker run --rm ci-test-base nimble test
