name: Feature Request
description: Suggest an idea for this project
title: "[Request] "
labels: ["request"]
# projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: discussions
    attributes:
      label: Discussions
      description: Please list relevant discussions if exists.
      placeholder: |
        - "#0"
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Please describe the problem you are facing.
      placeholder: |
        A clear and concise description of what the problem is.
        ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Please describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    id: Addition
    attributes:
      label: Additional Context
      description: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
    validations:
      required: false
