name: Build Pages
description: Build GitHub Pages
runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Base
      uses: docker/build-push-action@v4
      with:
        context: .
        target: base
        tags: ci-test-base
        cache-from: type=gha,scope=ci-test-base
        cache-to: type=gha,mode=max,scope=ci-test-base
        load: true
    - name: Nimble Doc2
      shell: sh
      run: |
        docker run --rm -v $(pwd)/docs:/ci-test/docs ci-test-base nimble doc2 -o:docs/developer src/ci_test.nim
        sudo chmod -c -R +rX docs | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done
        find docs -name *.idx | xargs rm
