on:
  push:
    branches:
    - feature/**

permissions: read-all

jobs:
  call nimble test:
    name: call nimble test
    uses: .github/workflows/on_workflow_call/nimble_test.yaml
    with:
      imagetag: ${{ github.ref_name }}
      username: ${{ vars.user }}
      password: ${{ secrets.password }}
  call build:
    name: call build
    uses: .github/workflows/on_workflow_call/build.yaml
    with:
      imagetag: ${{ github.ref_name }}
      username: ${{ vars.user }}
      password: ${{ secrets.password }}
