on:
  push:
    branches:
    - feature-*

jobs:
  call-nimble-test:
    name: call nimble test
    uses: ./.github/workflows/on_workflow_call__nimble_test.yaml
    with:
      imagetag: ${{ github.ref_name }}
