on:
  pull_request_review:
    types:
    - submitted
    branches:
    - main

permissions: read-all

env:
  password: ${{ secrets.password }}

jobs:
  call build:
    name: call build
    uses: ./.github/workflows/on_workflow_call__build.yaml
    env:
    with:
      imagetag: ${{ github.ref_name }}
      username: ${{ vars.user }}
      password: ${{ env.password }}
  stg deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo stg deploy
  stg system test:
    name: stg system test
    uses: ./.github/workflows/on_workflow_call__system_test.yaml
    env:
    with:
      imagetag: ${{ github.ref_name }}
      username: ${{ vars.user }}
      password: ${{ env.password }}
