on:
  push:
    branches:
    - feature-*

jobs:
  feature-build:
    name: Feature Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platforms:
        - linux/amd64
        - linux/arm64
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      uses: ./.github/actions/build
      with:
        imagetag: ${{ github.ref_name }}
        platform: ${{ matrix.platforms }}
        build_env: feature
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # TODO: check advanced option: https://nim-lang.org/docs/nimc.html
        # https://hl4.gitee.io/nim/nimc.html
  feature-nimble-test:
    name: Feature Nimble Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Nimble Test
      uses: ./.github/actions/nimble_test
