on:
  pull_request:
    types:
      - closed

jobs:
  delete-package-versions:
    name: Delete Package Versions
    runs-on: ubuntu-latest
    steps:
      - name: Docker Metadata Action
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=ref,event=pr
      - name: Get Version ID
        id: get-version-id
        shell: sh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -eu
          echo id=$(
            gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /user/packages/container/ci-test/versions \
              --jq '.[]|select(.name==${{ steps.meta.outputs.tags }})|.id' \
          ) >> $GITHUB_OUTPUT
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v4
        with:
          owner: ${{ github.repository_owner }}
          package-name: ci-test
          package-type: container
          package-version-ids: ${{ steps.get-version-id.outputs.id }}
