on:
  push:
    branches:
    - feature-*

permissions: read-all

jobs:
  call-nimble-test:
    name: call nimble test
    uses: ./.github/workflows/on_workflow_call__nimble_test.yaml
    with:
      imagetag: ${{ github.ref_name }}
      username: ${{ vars.user }}
    secrets:
      password: ${{ secrets.password }}
    needs: []
  call-build:
    name: call build
    uses: ./.github/workflows/on_workflow_call__build.yaml
    with:
      imagetag: ${{ github.ref_name }}
      username: ${{ vars.user }}
    secrets:
      password: ${{ secrets.password }}
    needs: []
