on:
  release:
    types:
    - published

permissions: read-all

env:
  password: ${{ secrets.password }}

jobs:
  env:
  call build:
    name: call build
    uses: ./.github/workflows/on_workflow_call__build.yaml
    env:
    with:
      imagetag: ${{ github.ref_name }}
      username: ${{ vars.user }}
      password: ${{ env.password }}
  prd deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo prd deploy
