on:
  workflow_call:
    inputs:
      imagetag:
        required: true
        type: string

jobs:
  build-tester:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Tester
      uses: docker/build-push-action@v2
      with:
        context: .
        target: tester
        tags: ghcr.io/${{ github.repository_owner }}/ci-test:${{ inputs.imagetag }}
        cache-from: type=gha,scope=${{ inputs.imagetag }}
        cache-to: type=gha,mode=max,scope=${{ inputs.imagetag }}
        push: true
  nimble-test:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/ci-test:${{ inputs.imagetag }}
    needs: build-tester
    steps:
    - name: Nimble Test
      run: |
        pwd || true
        ls -a || true
        nimble test
