on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  nimble-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      ref: ${{ inputs.ref }}
    - name: Nimble Test
      run: nimble test
