on:
  workflow_call:
    inputs:
      imagetag:
        required: true
        type: string

jobs:
  nimble-test:
    runs-on: ubuntu-latest
    steps:
    - name: Build Tester
      uses: docker/build-push-action@v2
      with:
        context: .
        target: tester
        tags: ghcr.io/${{ github.repository_owner }}/ci-test:${{ inputs.imagetag }}
        cache-from: type=gha,scope=${{ inputs.imagetag }}
        cache-to: type=gha,mode=max,scope=${{ inputs.imagetag }}
    - name: Nimble Test
      uses: ghcr.io/${{ github.repository_owner }}/ci-test:${{ inputs.imagetag }}
