on:
  workflow_call:
    inputs:
      imagetag:
        required: true
        type: string
      username:
        required: true
        type: string
    secrets:
      password:
        required: true

jobs:
  system-test:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ inputs.username }}/ci-test:${{ inputs.imagetag }}-builder
    steps:
    - run: echo system test
