on:
  workflow_call:
    inputs:
      imagetag:
        required: true
        type: string

jobs:
  nimble test:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ vars.user }}/ci-test:${{ inputs.imagetag }}-builder
    steps:
    - run: nimble test
