on:
  workflow_call:
    inputs:
      imagetag:
        required: true
        type: string
      username:
        required: true
        type: string
    # secrets:
    #   password:
    #     required: true

permissions: read-all

jobs:
  system-test:
    runs-on: ubuntu-latest
    steps:
    - run: echo system test
