on:
  workflow_call:
    inputs:
      imagetag:
        required: true
        type: string

jobs:
  nimble-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Tester
      uses: docker/build-push-action@v2
      with:
        context: .
        target: base
        tags: tester
        cache-from: type=gha,scope=${{ inputs.imagetag }}
    - name: Nimble Test
      run: docker run --rm -it -v=/tmp/testresults:/ci-test/testresults tester nimble test
    - name: Upload Test Result
      uses: actions/upload-artifact@v3
      with:
        name: testresults-${{ inputs.imagetag }}
        path: /tmp/testresults/testresults.html
